---
title: "Scraping"
output: html_document
---
```{r, include = FALSE}
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
```

Loading in the data

```{r}
# checkout the website below first
tour <- read_html("https://en.wikipedia.org/wiki/List_of_Tour_de_France_general_classification_winners")
tables <- html_nodes(tour, css = "table") 
tables  # have to guesstimate which table contains climate info
tour_data <- html_table(tables, header = TRUE, fill = TRUE)[[3]]    
# note: not html_text
as_tibble(tour_data)
head(tour_data, n=10)
```


#Stage Wins per Rider
(Not able to figure this out yet. Asking tomorrow)

```{r}
rec_stat <- read_html("https://en.wikipedia.org/wiki/Tour_de_France_records_and_statistics#Stage_wins_per_rider")
tables <- html_nodes(rec_stat, css = "table") 
stages_per_rider<- html_text(tables)[[3]]

stages_per_rider <- stages_per_rider %>%
  str_split( "(\n)|(\\[14\\])") %>%
  unlist()%>%
  str_subset("(.)+")



stages_per_rider <- c(stages_per_rider[1:40], 9, stages_per_rider[41:121])
stages_per_rider <- c(stages_per_rider[1:44], 9, stages_per_rider[45:122])
stages_per_rider <- c(stages_per_rider[1:60], 14, stages_per_rider[61:123])
stages_per_rider <- c(stages_per_rider[1:68], 16, stages_per_rider[69:124])
stages_per_rider <- c(stages_per_rider[1:72], 16, stages_per_rider[73:125])
stages_per_rider <- c(stages_per_rider[1:76], 16, stages_per_rider[77:126])
stages_per_rider <- c(stages_per_rider[1:80], 16, stages_per_rider[81:127])
stages_per_rider <- c(stages_per_rider[1:88], 21, stages_per_rider[89:128])
stages_per_rider <- c(stages_per_rider[1:92], 21, stages_per_rider[93:129])
stages_per_rider <- c(stages_per_rider[1:96], 21, stages_per_rider[97:130])
stages_per_rider <- c(stages_per_rider[1:100], 21, stages_per_rider[101:128])
stages_per_rider <- c(stages_per_rider[1:108], 26, stages_per_rider[109:129])
stages_per_rider <- c(stages_per_rider[1:112], 26, stages_per_rider[113:130])
stages_per_rider <- c(stages_per_rider[1:116], 26, stages_per_rider[117:131])
stages_per_rider <- c(stages_per_rider[1:120], 26, stages_per_rider[121:132])
stages_per_rider <- c(stages_per_rider[1:124], 26, stages_per_rider[125:133])
stages_per_rider <- c(stages_per_rider[1:128], 26, stages_per_rider[129:134])
stages_per_rider <- c(stages_per_rider[1:132], 26, stages_per_rider[133:135])

stages_per_rider <- as.tibble(matrix(stages_per_rider, byrow = TRUE, ncol = 4))

colnames(stages_per_rider) <- stages_per_rider[1,]

stages_per_rider <- stages_per_rider[-1,]
stages_per_rider
```

Removing the World wars from the winners data .
```{r}
tour_data <- tour_data %>%
  mutate_all(funs(ifelse(.=="World War II", NA, .))) %>%
  mutate_all(funs(ifelse(.=="World War I", NA, .)))

```



Doping Information
```{r}
# checkout the website below first
doping <- read_html("https://en.wikipedia.org/wiki/Doping_at_the_Tour_de_France")
dopingtables <- html_nodes(doping, css = "table") 
dopingtables  # have to guesstimate which table contains climate info
doping_data <- html_table(dopingtables, header = TRUE, fill = TRUE)[[3]]    

doping_tibble <- as_tibble(doping_data)
doping_tibble
head(doping_tibble, n=10)
```


Top 10 Winners
```{r}
doping <- read_html("https://en.wikipedia.org/wiki/Doping_at_the_Tour_de_France")
dopingtables <- html_nodes(doping, css = "table") 
dopingtables  # have to guesstimate which table contains climate info

`1998_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[5]]
`1998_tibble` <- as_tibble(`1998_data`) %>% 
  add_column(Year = rep("1998", 10), .before = "Rank")


`1999_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[6]]
`1999_tibble` <- as_tibble(`1999_data`)%>% 
  add_column(Year = rep("1999", 10), .before = "Rank")


`2000_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[7]]
`2000_tibble` <- as_tibble(`2000_data`)%>% 
  add_column(Year = rep("2000", 10), .before = "Rank")


`2001_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[8]]
`2001_tibble` <- as_tibble(`2001_data`)%>% 
  add_column(Year = rep("2001", 10), .before = "Rank")


`2002_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[9]]
`2002_tibble` <- as_tibble(`2002_data`)%>% 
  add_column(Year = rep("2002", 10), .before = "Rank")


`2003_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[10]]
`2003_tibble` <- as_tibble(`2003_data`)%>% 
  add_column(Year = rep("2003", 10), .before = "Rank")


`2004_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[11]]
`2004_tibble` <- as_tibble(`2004_data`)%>% 
  add_column(Year = rep("2004", 10), .before = "Rank")


`2005_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[12]]
`2005_tibble` <- as_tibble(`2005_data`) %>% 
  add_column(Year = rep("2005", 11), .before = "Rank")


`2006_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[13]]
`2006_tibble` <- as_tibble(`2006_data`)%>% 
  add_column(Year = rep("2006", 10), .before = "Rank")


`2007_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[14]]
`2007_tibble` <- as_tibble(`2007_data`)%>% 
  add_column(Year = rep("2007", 10), .before = "Rank")


`2008_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[15]]
`2008_tibble` <- as_tibble(`2008_data`)%>% 
  add_column(Year = rep("2008", 10), .before = "Rank")


`2009_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[16]]
`2009_tibble` <- as_tibble(`2009_data`)%>% 
  add_column(Year = rep("2009", 10), .before = "Rank")


`2010_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[17]]
`2010_tibble` <- as_tibble(`2010_data`)%>% 
  add_column(Year = rep("2010", 10), .before = "Rank")


`2011_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[18]]
`2011_tibble` <- as_tibble(`2011_data`)%>% 
  add_column(Year = rep("2011", 10), .before = "Rank")


`2012_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[19]]
`2012_tibble` <- as_tibble(`2012_data`)%>% 
  add_column(Year = rep("2012", 10), .before = "Rank")


`2013_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[20]]
`2013_tibble` <- as_tibble(`2013_data`)%>% 
  add_column(Year = rep("2013", 10), .before = "Rank")


`2014_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[21]]
`2014_tibble` <- as_tibble(`2014_data`)%>% 
  add_column(Year = rep("2014", 10), .before = "Rank")


`2015_data` <- html_table(dopingtables, header = TRUE, fill = TRUE)[[22]]
`2015_tibble` <- as_tibble(`2015_data`)%>% 
  add_column(Year = rep("2015", 10), .before = "Rank")

top_tens <- bind_rows(`1998_tibble`, `1999_tibble`, `2000_tibble`, `2001_tibble`, `2002_tibble`, `2003_tibble`, `2004_tibble`, `2005_tibble`, `2006_tibble`, `2007_tibble`, `2008_tibble`, `2009_tibble`, `2010_tibble`, `2011_tibble`, `2012_tibble`, `2013_tibble`, `2014_tibble`, `2015_tibble`)
```


```{r}
setwd("~/Mscs 264 F18/Submit Section B/TourProject")
write_rds(top_tens, "top_tens.rds")
write_rds(top_tens, "top_tens.rds")
write_rds(doping_tibble, "doping_tibble.rds")
write_rds(doping_tibble, "doping_tibble.rds")
write_rds(tour_data, "tour_data.rds")
write_csv(top_tens, "top_tens.csv")
```


##Comments for top_tens

```{r}
top_tencomments <- read_csv("~/Mscs 264 F18/Submit Section B/TourProject/top_tencomments.csv")

mergedtop_tens <- top_tens %>%
  mutate(Year = as.integer(Year)) %>%
  left_join(top_tencomments)

write_rds(mergedtop_tens, "mergedtop_tens.rds")
```





